src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__IsFollowing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Following</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__SubscriptionDate__c</fullName>
        <label>Subscription Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <formula>IF(
  NOT(ISBLANK(Charket__Contact__c)),
  &apos;Contact&apos;,
  IF(NOT(ISBLANK(Charket__Lead__c)),
     &apos;Lead&apos;,
     &apos;Follower&apos;
  )
)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatNotificationTemplate__c.object
<CustomObject>
    <fields>
        <fullName>Charket__TemplateId__c</fullName>
        <label>Template ID</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipName>WeChat_Templates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Notification Template</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Notification Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatQRCode__c.object
<CustomObject>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__Scene__c</fullName>
        <label>Scene</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__Ticket__c</fullName>
        <label>Ticket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Temporary</fullName>
                    <default>true</default>
                    <label>Temporary</label>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat QR Codes</relationshipLabel>
        <relationshipName>WeChatQRCode</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatResponse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Response</label>
        <referenceTo>Charket__WeChatResponse__c</referenceTo>
        <relationshipLabel>WeChat QR Codes</relationshipLabel>
        <relationshipName>WeChatQRCode</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WhatId__c</fullName>
        <label>Related To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MoreInfo__c</fullName>
        <label>More Info</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>WeChat QR Code</label>
    <nameField>
        <label>WeChat QR Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat QR Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/WeChatLeadControllerTest.cls
@isTest
public class WeChatLeadControllerTest
{
    private static Lead lead = createLead('12345678901', 'aa');
    private static Contact contact = createContact('12345678901', 'aa');
    private static Charket__WeChatAccount__c account = getWeChatAccount();
    private static Charket__WeChatFollower__c follower = getWeChatFollower(account.Id, lead.Id);
    private static Charket__WeChatQRCode__c qrCode = createQRCode(account.Id, 'test ticket');

    @isTest
    static void testInit()
    {
        WeChatLeadController controller = getWeChatLeadController();

        // openId is null
        String result = WeChatLeadController.init(null, '123', account.Id, '');
        System.assertEquals('{\"oauth_url\": \"\"}', result);

        // follower with lead
        result = WeChatLeadController.init(controller.EncryedOpenId, '123', account.Id, '');
        System.assert(result.contains(lead.LastName));

        // follower with contact
        follower.Charket__Lead__c = null;
        follower.Charket__Contact__c = contact.Id;
        update follower;
        result = WeChatLeadController.init(controller.EncryedOpenId, '123', account.Id, '');
        System.assert(result.contains(contact.LastName));

    }

    @isTest
    static void testSave()
    {
        WeChatLeadController controller = getWeChatLeadController();
        Campaign campaign = new Campaign(Name = 'acme', IsActive = true);
        insert campaign;

        CampaignMember member = new CampaignMember(
                CampaignId = campaign.Id, LeadId = lead.Id,
                Status = 'Sent');
        insert member;

        Charket__WeChatNotificationTemplate__c template = new Charket__WeChatNotificationTemplate__c(
            Charket__TemplateId__c = 'templateId'
        );
        insert template;
        
        // follower with lead
        String result = WeChatLeadController.save('bb', lead.LastName, 'acme@charket.com', 'companyStr', '0', campaign.Id,
        'Responded', controller.EncryedOpenId, template.Id, '', true, account.Id, qrCode.Id);
        System.assertEquals(null, result);

        // follower with contact
        follower.Charket__Lead__c = null;
        follower.Charket__Contact__c = contact.Id;
        update follower;

        result = WeChatLeadController.save('bb', lead.LastName, 'acme@charket.com', 'companyStr', '0', campaign.Id,
        'Responded', controller.EncryedOpenId, template.Id, '', true, account.Id, qrCode.Id);
        System.assertEquals(null, result);
    }
    
    @isTest
    static void testSaveWithContactEmail()
    {
        Contact contact2 = new Contact(AccountId = contact.AccountId, Email = 'acme.contact@charket.com',
            LastName = 'Test');
        insert contact2;
        
        WeChatLeadController controller = getWeChatLeadController();
        Campaign campaign = new Campaign(Name = 'acme', IsActive = true);
        insert campaign;
        
        contact.Email = '';
        update contact;
        
        follower.Charket__Lead__c = null;
        follower.Charket__Contact__c = contact.Id;
        update follower;
       
        String result = WeChatLeadController.save('bb', lead.LastName, 'acme.contact@charket.com', 'companyStr', '0', campaign.Id,
        'Responded', controller.EncryedOpenId, '', '', true, account.Id, qrCode.Id);
        
        Charket__WeChatFollower__c newFollower = [select Charket__Lead__c, Charket__Contact__c from Charket__WeChatFollower__c
                where Id = :follower.Id limit 1];
        System.assertEquals(newFollower.Charket__Contact__c, contact2.Id);
    }
    
    @isTest
    static void testSaveWithLeadEmail()
    {
        Lead lead2 = new Lead(Company = 'Charket', Email = 'acme.contact@charket.com',
            LastName = 'Test');
        insert lead2;
        
        WeChatLeadController controller = getWeChatLeadController();
        Campaign campaign = new Campaign(Name = 'acme', IsActive = true);
        insert campaign;
        
        contact.Email = '';
        update contact;
        
        follower.Charket__Lead__c = null;
        follower.Charket__Contact__c = contact.Id;
        update follower;
       
        String result = WeChatLeadController.save('bb', lead.LastName, 'acme.contact@charket.com', 'companyStr', '0', campaign.Id,
        'Responded', controller.EncryedOpenId, '', '', true, account.Id, qrCode.Id);
        
        Charket__WeChatFollower__c newFollower = [select Charket__Lead__c, Charket__Contact__c from Charket__WeChatFollower__c
                where Id = :follower.Id limit 1];
        System.assertEquals(newFollower.Charket__Contact__c, null);
        System.assertEquals(newFollower.Charket__Lead__c, lead2.Id);
    }

    private static Charket__WeChatAccount__c getWeChatAccount()
    {
        Charket__WeChatAccount__c wechatAccount = new Charket__WeChatAccount__c(
                Name = 'TestAcount', Charket__WeChatOriginId__c = 'test origin',
                Charket__Type__c = 'subscribe'
            );
        insert wechatAccount;
        return wechatAccount;
    }

    private static WeChatLeadController getWeChatLeadController()
    {
        PageReference WeChatLeadPage = Page.WeChatLead;
        WeChatLeadPage.getParameters().put('code', '123123');
        WeChatLeadPage.getParameters().put('accId', account.Id);
        WeChatLeadPage.getParameters().put('qrId', qrCode.Id);
        Test.setCurrentPage(WeChatLeadPage);
        WeChatLeadController controller = new WeChatLeadController();
        return controller;
    }

    private static Charket__WeChatFollower__c getWeChatFollower(Id accountId, Id leadId)
    {
        Charket__WeChatFollower__c wechatFollower = new Charket__WeChatFollower__c(
                Charket__OpenId__c = 'OPENID', Charket__WeChatAccount__c = account.Id,
                Charket__IsFollowing__c = true, Charket__SubscriptionDate__c = System.now(),
                Charket__Lead__c = lead.Id
            );
        insert wechatFollower;
        return wechatFollower;
    }

    private static Charket__WeChatQRCode__c createQRCode(String accountId, String ticket)
    {
        Campaign campaign = new Campaign(Name = 'acme', IsActive = true);
        insert campaign;

        Charket__WeChatResponse__c response = new Charket__WeChatResponse__c(
                Name = 'Sign in', Charket__WeChatAccount__c = accountId,
                Charket__WhatId__c = campaign.Id, Charket__UsedFor__c = 'Welcome Message',
                Charket__IsActive__c = true
            );
        insert response;

        Charket__WeChatMessage__c message = new Charket__WeChatMessage__c(
                Name = 'Form Link', Charket__Type__c = 'Text Message',
                Charket__TextBody__c = 'https://ge.customer.charket.com.cn/wechatlead'
            );
        insert message;

        Charket__WeChatResponseItem__c responseItem = new Charket__WeChatResponseItem__c(
                Charket__WeChatResponse__c = response.Id,
                Charket__WeChatMessage__c = message.Id
            );
        insert responseItem;
        Charket__WeChatQRCode__c newQRCode = new Charket__WeChatQRCode__c(
                Charket__WeChatAccount__c = accountId, Charket__Scene__c = '123',
                Charket__Type__c = 'Temporary', Charket__WeChatResponse__c = response.Id,
                Charket__WhatId__c = campaign.Id,
                Charket__IsActive__c = true, Charket__Ticket__c = ticket,
                MoreInfo__c = '{"IsRegister":true, "HasConfirm":true, "EnterPhoneLabel":"12345678901", "CampaignMemberStatus":"Sent", "HasRegisterLabel":"111", "IsPrint":true}'
            );
        insert newQRCode;

        return newQRCode;
    }

    private static Lead createLead(String phone, String lastName)
    {
        Lead newLead = new Lead(
                FirstName = 'Test', LastName = lastName, Phone = phone, Email = 'test@meginfo.com',
                Company = 'Meginfo', Title = '其他'
            );
        insert newLead;
        return newLead;
    }

    private static Contact createContact(String phone, String lastName)
    {
        Account acc = new Account(Name = 'Meginfo');
        insert acc;
        Contact newContact = new Contact(
                FirstName = 'Test', LastName = lastName, Phone = phone, Email = 'test@meginfo.com',
                AccountId = acc.Id
            );
        insert newContact;
        return newContact;
    }
}