src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatTranscript__c.object
<CustomObject>
    <fields>
        <fullName>Charket__DeliveredMethod__c</fullName>
        <label>Delivered Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Mass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__FollowerOpenId__c</fullName>
        <externalId>true</externalId>
        <label>Follower Open ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__IsClosed__c</fullName>
        <formula>if(ISPICKVAL(Charket__Status__c, &apos;Completed&apos;)||ISPICKVAL(Charket__Status__c, &apos;Missed&apos;)||ISPICKVAL(Charket__Status__c, &apos;Blocked&apos;), true, false)</formula>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__StartedBy__c</fullName>
        <description>The way the chat was started: by the agent or the follower.</description>
        <label>Started By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Follower</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__UnreadCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unread Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAgent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Agent</label>
        <referenceTo>Charket__WeChatAgent__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatFollower__c</fullName>
        <label>WeChat Follower</label>
        <referenceTo>Charket__WeChatFollower__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WeChat Transcript</label>
    <nameField>
        <displayFormat>WT-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Transcripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/assign-agents/src/objects/WeChatAgentAssignment__c.object
<CustomObject>
    <fields>
        <fullName>WeChatAgentSkill__c</fullName>
        <label>WeChat Agent Skill</label>
        <referenceTo>WeChatAgentSkill__c</referenceTo>
        <relationshipLabel>WeChat Agent Assignments</relationshipLabel>
        <relationshipName>WeChatAgentAssignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WeChatAgent__c</fullName>
        <label>WeChat Agent</label>
        <referenceTo>Charket__WeChatAgent__c</referenceTo>
        <relationshipLabel>WeChat Agent Assignments</relationshipLabel>
        <relationshipName>WeChatAgentAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WeChat Agent Assignment</label>
    <nameField>
        <displayFormat>WAA{0000000}</displayFormat>
        <label>WeChat Agent Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Agent Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/assign-agents/src/objects/WeChatAgentSkill__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GV</fullName>
                </value>
                <value>
                    <fullName>GT</fullName>
                </value>
                <value>
                    <fullName>GE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>University__c</fullName>
        <label>University</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>University_Global</valueSetName>
        </valueSet>
    </fields>
    <label>WeChat Agent Skill</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>WeChat Agent Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Agent Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/assign-agents/src/classes/WeChatFollowerTriggerHandler.cls
public class WeChatFollowerTriggerHandler extends TriggerHandler
{
    List<Charket__WeChatFollower__c> newFollowers;
    List<Charket__WeChatFollower__c> oldFollowers;

    public WeChatFollowerTriggerHandler()
    {
        newFollowers = (List<Charket__WeChatFollower__c>)Trigger.new;
        oldFollowers = (List<Charket__WeChatFollower__c>)Trigger.old;
    }
    public override void afterUpdate()
    {
        String agentId;
        String wechatAccountId = newFollowers[0].Charket__WeChatAccount__c;
        String agentStatus = 'Don\'t Accept Chats';
        String university = newFollowers[0].University__c;
        String product = newFollowers[0].Interested_Product__c;

        Charket__WeChatFollower__c newFollower = newFollowers[0];
        Charket__WeChatFollower__c oldFollower = oldFollowers[0];

        if(newFollowers.size() > 1 || String.isBlank(newFollower.Interested_Product__c) || String.isBlank(newFollower.University__c))
        {
            return;
        }

        if(!newFollower.Interested_Product__c.equals(oldFollower.Interested_Product__c) ||
            !newFollower.University__c.equals(oldFollower.University__c))
        {
            agentId = WeChatAgentCustomAssigmentUtil.getAgentId(newFollower);
        }

        if(String.isNotBlank(agentId))
        {
            List<Charket__WeChatTranscript__c> wechatTranscripts = [select Id, Charket__Status__c, Charket__WeChatAgent__c,
                    Charket__WeChatAgent__r.Name, Charket__WeChatFollower__r.Charket__WeChatAccount__c, Charket__FollowerOpenId__c
                    from Charket__WeChatTranscript__c
                    where Charket__Status__c != 'Completed'
                    and Charket__IsClosed__c = false
                    and Charket__WeChatFollower__r.Charket__WeChatAccount__c = :newFollower.Charket__WeChatAccount__c
                    and Charket__WeChatFollower__r.Charket__OpenId__c = :newFollower.Charket__OpenId__c order by LastModifiedDate desc limit 1];

            try
            {
                String query = 'select Id,(select Id, WeChatAgent__c from WeChatAgentAssignments__r where WeChatAgent__r.Charket__IsActive__c = true ' +
                            'and WeChatAgent__r.Charket__WeChatAccount__c = :wechatAccountId and WeChatAgent__r.Charket__Status__c != :agentStatus) from WeChatAgentSkill__c ' +
                            'where University__c = :university and Product__c = :product';
                List<WeChatAgentSkill__c> skills = Database.query(query);
                if(skills.size() > 0)
                {
                    for(WeChatAgentAssignment__c assignment : skills[0].WeChatAgentAssignments__r)
                    {
                        if(wechatTranscripts.size() > 0 && wechatTranscripts[0].Charket__WeChatAgent__c != null &&
                            (wechatTranscripts[0].Charket__WeChatAgent__c).equals(assignment.WeChatAgent__c))
                        {
                            system.debug('return::' + 'return');
                            return;
                        }
                    }
                }

                if(wechatTranscripts.size() > 0)
                {
                    wechatTranscripts[0].Charket__Status__c = 'Completed';
                    upsert wechatTranscripts;
                }

                Charket__WeChatTranscript__c transcript = new Charket__WeChatTranscript__c();
                transcript.Charket__WeChatAgent__c = agentId;
                system.debug('agentId1::' + agentId);
                transcript.Charket__Status__c = 'In Progress';
                transcript.Charket__WeChatFollower__c = newFollower.Id;
                transcript.Charket__DeliveredMethod__c = 'Direct';
                transcript.Charket__UnreadCount__c = 0;
                transcript.Charket__StartedBy__c = 'Follower';
                transcript.Charket__FollowerOpenId__c = newFollower.Charket__OpenId__c;
                transcript.Charket__IsActive__c = true;

                upsert transcript transcript.Charket__FollowerOpenId__c;
                system.debug('transcriptid::' + transcript);
            }
            catch(Exception e)
            {
                System.debug(e.getMessage() + e.getLineNumber());
            }
        }
    }
}