src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>BadgeCompany__c</fullName>
        <label>Badge Company</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BadgeId__c</fullName>
        <label>Badge ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BadgeName__c</fullName>
        <label>Badge Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BadgePrintDate__c</fullName>
        <label>Badge Print Date</label>
        <type>DateTime</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/UpdateFollowerInfo.cls
@RestResource(urlMapping='/UpdateFollower/*')
global class UpdateFollowerInfo
{
	@HttpPost
    global static void doPost()
    {
        Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(
            Id = 'a0O0l00000139ulEAA',
            BadgeId__c = 'a0y0l000000AO1lAAG',
            BadgeName__c = 'Gary',
            BadgeCompany__c = 'Charket5',
            BadgePrintDate__c = Datetime.now()
        );
        update follower;
    }
    
    @HttpGet
    global static void doGet()
    {
        Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(
            Id = 'a0O0l00000139ulEAA',
            BadgeId__c = 'a0y0l000000AO1lAAG',
            BadgeName__c = 'Gary',
            BadgeCompany__c = 'Charket5',
            BadgePrintDate__c = Datetime.now()
        );
        update follower;
    }
}