src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__IsFollowing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Following</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <formula>IF(
  NOT(ISBLANK(Charket__Contact__c)),
  &apos;Contact&apos;,
  IF(NOT(ISBLANK(Charket__Lead__c)),
     &apos;Lead&apos;,
     &apos;Follower&apos;
  )
)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatQRCode__c.object
<CustomObject>
    <fields>
        <fullName>Charket__CampaignMemberStatus__c</fullName>
        <label>Campaign Member Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__Ticket__c</fullName>
        <label>Ticket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Temporary</fullName>
                    <default>true</default>
                    <label>Temporary</label>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat QR Codes</relationshipLabel>
        <relationshipName>WeChatQRCode</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WhatId__c</fullName>
        <label>Related To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MoreInfo__c</fullName>
        <label>More Info</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>WeChat QR Code</label>
    <nameField>
        <label>WeChat QR Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat QR Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatTranscript__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Charket__DeliveredMethod__c</fullName>
        <label>Delivered Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Mass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__FollowerOpenId__c</fullName>
        <externalId>true</externalId>
        <label>Follower Open ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__StartedBy__c</fullName>
        <description>The way the chat was started: by the agent or the follower.</description>
        <label>Started By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Follower</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__UnreadCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unread Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatFollower__c</fullName>
        <label>WeChat Follower</label>
        <referenceTo>Charket__WeChatFollower__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WeChat Transcript</label>
    <nameField>
        <displayFormat>WT-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Transcripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/EventCustomHandlerTest.cls
@isTest
private class EventCustomHandlerTest
{
    @isTest
    static void onFollowerScanTest()
    {
        Charket.WeChatApiEvent.Scan scan = new Charket.WeChatApiEvent.Scan();
        scan.FromUserId = 'test user id';
        scan.Ticket = 'test ticket';
        scan.ToUserId = 'test to user Id';
        
        Lead lead = new Lead(LastName = 'acme',
                Company = 'acme',
                LeadSource = 'WeChat',
                Email = 'acme@acme.com'
            );
        insert lead;

        Charket__WeChatAccount__c account = new Charket__WeChatAccount__c(
                Name = 'test account',
                Charket__WeChatOriginId__c = 'test to user id',
                Charket__Type__c = 'subscribe'
            );
        insert account;
        
        Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(
                Charket__OpenId__c = 'test user id',
                Charket__Lead__c = lead.Id,
                Charket__WeChatAccount__c = account.Id,
                Charket__IsFollowing__c = true
            );
        insert follower;

        Campaign campaign = new Campaign(
                Name = 'test',
                IsActive = true
            );
        insert campaign;
        
        CampaignMember member = new CampaignMember(CampaignId = campaign.Id, LeadId = lead.Id, Status = 'Attended');
        insert member;

        Charket__WeChatQRCode__c qrcode = new Charket__WeChatQRCode__c(
            Charket__Ticket__c = 'test ticket',
            Charket__IsActive__c = true,
            Charket__WhatId__c = campaign.Id,
            Charket__CampaignMemberStatus__c = member.Status,
            MoreInfo__c = '{"IsAttended":true,"CampaignMemberStatus":"Attended","MessageId":null,"IsPrint":true,"FormBanner":"abc.jpg","FormTitle":"Charket"}'
        );
        insert qrcode;
        
        Charket__WeChatTranscript__c transcript = new Charket__WeChatTranscript__c(
            Charket__DeliveredMethod__c = 'Direct',
            Charket__FollowerOpenId__c = 'test user id',
            Charket__StartedBy__c = 'Follower',
            Charket__UnreadCount__c = 1,
            Charket__WeChatFollower__c = follower.Id,
            Charket__IsActive__c = true,
            Charket__Status__c = 'New'
        );
        
        insert transcript;

        Test.startTest();
        EventCustomHandler handler = new EventCustomHandler();
        handler.onFollowerScan(scan);
        Charket.WeChatApiMessage.Text text = (Charket.WeChatApiMessage.Text)handler.onFollowerScan(scan);
        Test.stopTest();
    }
    
    @isTest
    static void notFollowerScanTest()
    {
        Charket.WeChatApiEvent.Scan scan = new Charket.WeChatApiEvent.Scan();
        scan.FromUserId = 'test user id';
        scan.Ticket = 'test ticket';
        scan.ToUserId = 'test to user Id';
        
        Lead lead = new Lead(LastName = 'acme',
                Company = 'acme',
                LeadSource = 'WeChat',
                Email = 'acme@acme.com'
            );
        insert lead;

        Charket__WeChatAccount__c account = new Charket__WeChatAccount__c(
                Name = 'test account',
                Charket__WeChatOriginId__c = 'test to user id',
                Charket__Type__c = 'subscribe'
            );
        insert account;
        
        Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(
                Charket__OpenId__c = 'test user id',
                Charket__Lead__c = lead.Id,
                Charket__WeChatAccount__c = account.Id,
                Charket__IsFollowing__c = false
            );
        insert follower;

        Campaign campaign = new Campaign(
                Name = 'test',
                IsActive = true
            );
        insert campaign;
        
        CampaignMember member = new CampaignMember(CampaignId = campaign.Id, LeadId = lead.Id, Status = 'Attended');
        insert member;

        Charket__WeChatQRCode__c qrcode = new Charket__WeChatQRCode__c(
            Charket__Ticket__c = 'test ticket',
            Charket__IsActive__c = true,
            Charket__WhatId__c = campaign.Id,
            Charket__CampaignMemberStatus__c = member.Status,
            MoreInfo__c = '{"IsAttended":true,"CampaignMemberStatus":"Attended","MessageId":null,"IsPrint":true,"FormBanner":"abc.jpg","FormTitle":"Charket"}'
        );
        insert qrcode;
        
        Charket__WeChatTranscript__c transcript = new Charket__WeChatTranscript__c(
            Charket__DeliveredMethod__c = 'Direct',
            Charket__FollowerOpenId__c = 'test user id',
            Charket__StartedBy__c = 'Follower',
            Charket__UnreadCount__c = 1,
            Charket__WeChatFollower__c = follower.Id,
            Charket__IsActive__c = true,
            Charket__Status__c = 'New',
            Charket__Body__c = 'abcd'
        );
        
        insert transcript;
        
        Test.startTest();
        EventCustomHandler handler = new EventCustomHandler();
        handler.onNotFollowerScan(scan);
        Charket.WeChatApiMessage.Text text = (Charket.WeChatApiMessage.Text)handler.onNotFollowerScan(scan);
        Test.stopTest();
        
        List<Charket__WeChatTranscript__c> transcripts = [select Charket__Body__c from Charket__WeChatTranscript__c];
        System.assertEquals(transcripts[0].Charket__Body__c, null);
    }
    
    @isTest
    static void testNoMemberCampaign()
    {
        Charket.WeChatApiEvent.Scan scan = new Charket.WeChatApiEvent.Scan();
        scan.FromUserId = 'test user id';
        scan.Ticket = 'test ticket';
        scan.ToUserId = 'test to user Id';
        
        Contact contact = new Contact(LastName = 'acme', Email = 'acme@acme.com');
        insert contact;

        Charket__WeChatAccount__c account = new Charket__WeChatAccount__c(
            Name = 'test account',
            Charket__WeChatOriginId__c = 'test to user id',
            Charket__Type__c = 'subscribe'
        );
        insert account;
        
        Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(
                Charket__OpenId__c = 'test user id',
                Charket__Contact__c = contact.Id,
                Charket__WeChatAccount__c = account.Id,
                Charket__IsFollowing__c = true
            );
        insert follower;

        Campaign campaign = new Campaign(
            Name = 'test',
            IsActive = true
        );
        insert campaign;
        
        Campaign campaign1 = new Campaign(
            Name = 'test1',
            IsActive = true
        );
        insert campaign1;
        
        CampaignMember member = new CampaignMember(CampaignId = campaign1.Id, ContactId = contact.Id, Status = 'Attended');
        insert member;

        Charket__WeChatQRCode__c qrcode = new Charket__WeChatQRCode__c(
            Charket__Ticket__c = 'test ticket',
            Charket__IsActive__c = true,
            Charket__WhatId__c = campaign.Id,
            Charket__CampaignMemberStatus__c = member.Status,
            MoreInfo__c = '{"IsAttended":true,"CampaignMemberStatus":"Attended","MessageId":null,"IsPrint":true,"FormBanner":"abc.jpg","FormTitle":"Charket"}'
        );
        insert qrcode;
        
        Charket__WeChatTranscript__c transcript = new Charket__WeChatTranscript__c(
            Charket__DeliveredMethod__c = 'Direct',
            Charket__FollowerOpenId__c = 'test user id',
            Charket__StartedBy__c = 'Follower',
            Charket__UnreadCount__c = 1,
            Charket__WeChatFollower__c = follower.Id,
            Charket__IsActive__c = true,
            Charket__Status__c = 'New'
        );
        
        insert transcript;

        Test.startTest();
        EventCustomHandler handler = new EventCustomHandler();
        handler.onFollowerScan(scan);
        Charket.WeChatApiMessage.Text text = (Charket.WeChatApiMessage.Text)handler.onFollowerScan(scan);
        Test.stopTest();
        
        List<CampaignMember> members = [select CampaignId from CampaignMember];
        System.assertEquals(members[1].CampaignId, campaign.Id);
    }
}