src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__IsFollowing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Following</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatQRCode__c.object
<CustomObject>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__Ticket__c</fullName>
        <label>Ticket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat QR Codes</relationshipLabel>
        <relationshipName>WeChatQRCode</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatResponse__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Response</label>
        <referenceTo>Charket__WeChatResponse__c</referenceTo>
        <relationshipLabel>WeChat QR Codes</relationshipLabel>
        <relationshipName>WeChatQRCode</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WhatId__c</fullName>
        <label>Related To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MoreInfo__c</fullName>
        <label>More Info</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>WeChat QR Code</label>
    <nameField>
        <label>WeChat QR Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat QR Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatTranscript__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Charket__DeliveredMethod__c</fullName>
        <label>Delivered Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Mass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__FollowerOpenId__c</fullName>
        <externalId>true</externalId>
        <label>Follower Open ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__IsClosed__c</fullName>
        <formula>if(ISPICKVAL(Charket__Status__c, &apos;Completed&apos;)||ISPICKVAL(Charket__Status__c, &apos;Missed&apos;)||ISPICKVAL(Charket__Status__c, &apos;Blocked&apos;), true, false)</formula>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatFollower__c</fullName>
        <label>WeChat Follower</label>
        <referenceTo>Charket__WeChatFollower__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WeChat Transcript</label>
    <nameField>
        <displayFormat>WT-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Transcripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/EventCustomHandler.cls
global without sharing class EventCustomHandler extends Charket.CharketEventHandler
{
    global override Charket.WeChatApiMessage onFollowerScan(Charket.WeChatApiEvent.Scan event)
    {
        List<Charket__WeChatQRCode__c> qrCodes = [select Charket__WhatId__c,
                Charket__WeChatResponse__c, Charket__WeChatAccount__c, MoreInfo__c
                from Charket__WeChatQRCode__c
                where Charket__Ticket__c != null and Charket__Ticket__c = :event.Ticket
                and Charket__IsActive__c = true and Charket__WhatId__c != null limit 1];
        if(qrCodes.size() > 0 && String.isNotBlank(qrCodes[0].MoreInfo__c) && qrCodes[0].MoreInfo__c.contains('{'))
        {
            Map<String, Object> moreInfo = (Map<String, Object>) JSON.deserializeUntyped(qrCodes[0].MoreInfo__c);
            
            Boolean isAccpeted = moreInfo.containsKey('IsAccepted') ? (Boolean)moreInfo.get('IsAccepted') : false;
            Boolean isAttended = moreInfo.containsKey('IsAttended') ? (Boolean)moreInfo.get('IsAttended') : false;
            if(isAccpeted || isAttended)
            {
                return dealScanEventToRegister(event, moreInfo, qrCodes[0], isAccpeted);
            }
        }

        return null;
    }

    global override Charket.WeChatApiMessage onNotFollowerScan(Charket.WeChatApiEvent.Scan event)
    {
        return onFollowerScan(event);
    }

    private static Charket.WeChatApiMessage dealScanEventToRegister(Charket.WeChatApiEvent.Scan event, Map<String, Object> moreInfo, Charket__WeChatQRCode__c qrCode, Boolean isAccepted)
    {
        String text = '';
        List<Charket__WeChatTranscript__c> transcripts = [select Id, Charket__Body__c, Charket__FollowerOpenId__c, Charket__WeChatFollower__c,
                 Charket__WeChatFollower__r.Charket__Lead__c, Charket__WeChatFollower__r.Charket__Contact__c,
                Charket__WeChatFollower__r.Charket__OpenId__c, Charket__WeChatFollower__r.Charket__IsFollowing__c,
                Charket__WeChatFollower__r.Charket__Lead__r.Email, Charket__WeChatFollower__r.Charket__Lead__r.FirstName,
                Charket__WeChatFollower__r.Charket__Lead__r.LastName, Charket__WeChatFollower__r.Charket__Contact__r.FirstName,
                Charket__WeChatFollower__r.Charket__Contact__r.Email, Charket__WeChatFollower__r.Charket__Contact__r.LastName,
                Charket__WeChatFollower__r.Charket__Lead__r.Company, Charket__WeChatFollower__r.Charket__Contact__r.Account.Name
                from Charket__WeChatTranscript__c
                where Charket__IsClosed__c = false and Charket__DeliveredMethod__c = 'Direct'
                and Charket__FollowerOpenId__c = :event.FromUserId limit 1];
        if(transcripts.size() > 0)
        {
            String leadId = transcripts[0].Charket__WeChatFollower__r.Charket__Lead__c;
            String contactId = transcripts[0].Charket__WeChatFollower__r.Charket__Contact__c;
            String leadOrContactId = String.isNotBlank(contactId) ? contactId : leadId;
            
            String campaignMemberStatus = moreInfo.containsKey('CampaignMemberStatus') ? (String)moreInfo.get('CampaignMemberStatus') : (isAccepted ? 'Accepted' : 'Attended');
            String hasLabel = isAccepted ? '您已报名成功' : '您已签到成功';
            String messageId = moreInfo.containsKey('MessageId') ? (String)moreInfo.get('MessageId') : null;
            String templateId = moreInfo.containsKey('TemplateId') ? (String)moreInfo.get('TemplateId') : null;
            Boolean isPrint = moreInfo.containsKey('IsPrint') ? (Boolean)moreInfo.get('IsPrint') : false;

            if((leadId != null && transcripts[0].Charket__WeChatFollower__r.Charket__Lead__r.Email != null)
                || (contactId != null && transcripts[0].Charket__WeChatFollower__r.Charket__Contact__r.Email != null))
            {
                if(!transcripts[0].Charket__WeChatFollower__r.Charket__IsFollowing__c)
                {
                    Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(
                            Charket__IsFollowing__c = true, Charket__OpenId__c = event.FromUserId);
                    upsert follower Charket__OpenId__c;
                }
                
                String firstName = contactId != null ? transcripts[0].Charket__WeChatFollower__r.Charket__Contact__r.FirstName 
                         : transcripts[0].Charket__WeChatFollower__r.Charket__Lead__r.FirstName;
                String lastName = contactId != null ? transcripts[0].Charket__WeChatFollower__r.Charket__Contact__r.LastName
                         : transcripts[0].Charket__WeChatFollower__r.Charket__Lead__r.LastName;
                String badgeName = String.isNotBlank(firstName) && String.isNotBlank(lastName) ?
                        (WeChatLeadController.containsChineseCharacters(firstName) && WeChatLeadController.containsChineseCharacters(lastName)
                            ? (lastName + firstName) : (firstName + ' ' + lastName)) : null;
                        
                String badgeCompany = contactId != null ? transcripts[0].Charket__WeChatFollower__r.Charket__Contact__r.Account.Name 
                        : transcripts[0].Charket__WeChatFollower__r.Charket__Lead__r.Company;
                        
                
                List<CampaignMember> members = [Select Id, Name, Status, LeadId, ContactId from CampaignMember
                        where CampaignId =: qrCode.Charket__WhatId__c
                        and ((LeadId =: leadId and LeadId != null)
                            or (ContactId =: contactId and ContactId != null))];
                if(members.size() > 0)
                {
                    emptyTranscriptBody(transcripts[0]);

                    if(members[0].Status == campaignMemberStatus)
                    {
                        text = hasLabel;
                        return new Charket.WeChatApiMessage.Text(text);
                    }
                    else
                    {
                        members[0].Status = campaignMemberStatus;
                        update members[0];

                        WeChatLeadController.sendTemplateNotification(members[0].Id, templateId, messageId, leadOrContactId);
                        WeChatLeadController.updateFollowerPrintFields(isPrint, transcripts[0].Charket__WeChatFollower__c, badgeName, badgeCompany, qrCode.Id);
                        return new Charket.WeChatApiMessage.Text('');
                    }
                }
                else
                {
                    emptyTranscriptBody(transcripts[0]);

                    CampaignMember member = new CampaignMember(
                        Status = campaignMemberStatus,
                        CampaignId = qrCode.Charket__WhatId__c,
                        LeadId = leadId,
                        ContactId = contactId
                    );
                    insert member;
                    WeChatLeadController.sendTemplateNotification(member.Id, templateId, messageId, leadOrContactId);
                    WeChatLeadController.updateFollowerPrintFields(isPrint, transcripts[0].Charket__WeChatFollower__c, badgeName, badgeCompany, qrCode.Id);
                    return new Charket.WeChatApiMessage.Text('');
                }
            }
        }
        return null;
    }

    private static void emptyTranscriptBody(Charket__WeChatTranscript__c transcript)
    {
        if(String.isNotBlank(transcript.Charket__Body__c))
        {
            transcript = new Charket__WeChatTranscript__c(
                    Charket__Body__c = null,
                    Charket__FollowerOpenId__c = transcript.Charket__FollowerOpenId__c
            );
            upsert transcript Charket__FollowerOpenId__c;
        }
    }
    
    public class Session
    {
        public Session() {}

        public Session(String sessionSequence, Map<String, String> sessionData)
        {
            this.SessionSequence = sessionSequence;
            this.SessionData = sessionData;
        }

        public String SessionSequence { get; set; }
        public Map<String, String> SessionData { get; set; }
    }
}