src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatQRCode__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Ticket__c</fullName>
        <label>Ticket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WhatId__c</fullName>
        <label>Related To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>WeChat QR Code</label>
    <nameField>
        <label>WeChat QR Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat QR Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/CharketScanEmailQRCodeHandlerTest.cls
@isTest
private class CharketScanEmailQRCodeHandlerTest
{
    @testSetup static void setup() 
    {
        Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(Charket__OpenId__c = 'client_abc123');
        insert follower;
    }

    @isTest
    private static void testLeadCharketScanEmailQRCodeHandler()
    {
        Lead lead = new Lead(LastName = 'anna', Company = 'Hello');
        insert lead;

        Charket__WeChatQRCode__c qrCode = new Charket__WeChatQRCode__c(Charket__Ticket__c = '00000000000000000', Charket__WhatId__c = lead.Id);
        insert qrCode;

        CharketScanEmailQRCodeHandler testHandler = new CharketScanEmailQRCodeHandler();

        testHandler.handleQRCode(null);

        List<Charket__WeChatFollower__c> followers = [select Id from Charket__WeChatFollower__c where Charket__Lead__c = :lead.Id];
        System.assert(followers.size() > 0);
    }

    @isTest
    private static void testContactCharketScanEmailQRCodeHandler()
    {
        Contact contact = new Contact(LastName = 'anna');
        insert contact;

        Charket__WeChatQRCode__c qrCode = new Charket__WeChatQRCode__c(Charket__Ticket__c = '00000000000000000', Charket__WhatId__c = contact.Id);
        insert qrCode;
        
        CharketScanEmailQRCodeHandler testHandler = new CharketScanEmailQRCodeHandler();

        testHandler.handleQRCode(null);

        List<Charket__WeChatFollower__c> followers = [select Id from Charket__WeChatFollower__c where Charket__Contact__c = :contact.Id];
        System.assert(followers.size() > 0);
    }
}