src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__IsFollowing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Following</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <formula>IF(
  NOT(ISBLANK(Charket__Contact__c)),
  &apos;Contact&apos;,
  IF(NOT(ISBLANK(Charket__Lead__c)),
     &apos;Lead&apos;,
     &apos;Follower&apos;
  )
)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/CharketFollowerPrintActionTest.cls
@isTest
private class CharketFollowerPrintActionTest
{
    @isTest
    static void updateFollowerPrintTest()
    {
    	Lead lead = new Lead(LastName = 'acme',
	            Company = 'acme',
	            LeadSource = 'WeChat'
	        );
        insert lead;

        Charket__WeChatAccount__c account = new Charket__WeChatAccount__c(
	            Name = 'test account',
	            Charket__WeChatOriginId__c = 'test123',
	            Charket__Type__c = 'subscribe'
	        );
        insert account;
        
    	Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(
    			Charket__OpenId__c = 'test',
    			Charket__Lead__c = lead.Id,
    			Charket__WeChatAccount__c = account.Id,
    			Charket__IsFollowing__c = true
    		);
    	insert follower;

        List<CharketFollowerPrintAction.UpdateFollowerPrintRequest> requests = new List<CharketFollowerPrintAction.UpdateFollowerPrintRequest>();
        CharketFollowerPrintAction.UpdateFollowerPrintRequest request  = new CharketFollowerPrintAction.UpdateFollowerPrintRequest();
        
        request.accountId = account.Id;
        request.whoId = lead.Id;
        request.objectId = follower.Id;
        requests.add(request);

        Test.startTest();
        CharketFollowerPrintAction.updateFollowerPrint(requests);
        Test.stopTest();
    }
}