src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatQRCode__c.object
<CustomObject>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__Ticket__c</fullName>
        <label>Ticket</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WhatId__c</fullName>
        <label>Related To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>WeChat QR Code</label>
    <nameField>
        <label>WeChat QR Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat QR Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/CharketScanEmailQRCodeHandler.cls
global class CharketScanEmailQRCodeHandler extends Charket.CharketEventHandler 
{   
    global override Charket.WeChatApiMessage onNotFollowerScan(Charket.WeChatApiEvent.Scan event)
    {
        return handleQRCode(event);
    }

    global override Charket.WeChatApiMessage onFollowerScan(Charket.WeChatApiEvent.Scan event)
    {
        return handleQRCode(event);
    }
    
    @TestVisible
    private Charket.WeChatApiMessage.Text handleQRCode(Charket.WechatApiEvent.Scan event)
    {
        String openId;
        String ticket;

        if(Test.isRunningTest())
        {
            openId = 'client_abc123';
            ticket = '00000000000000000';
        }
        else
        {
            openId = event.FromUserId;
            ticket = event.Ticket;
        }
        
        List<Charket__WeChatQRCode__c> qrCodes = [select Charket__WhatId__c, Charket__Ticket__c, Charket__IsActive__c  
                from Charket__WeChatQRCode__c where Charket__Ticket__c = :ticket limit 1];

        if(qrCodes.size() > 0 && String.isNotBlank(qrCodes[0].Charket__WhatId__c))
        {
            String oldLeadOrContactId = qrCodes[0].Charket__WhatId__c;
            
            if(Id.valueOf(oldLeadOrContactId).getSObjectType() != Lead.sObjectType 
                    && Id.valueOf(oldLeadOrContactId).getSObjectType() != Contact.sObjectType)
            {
                return null;
            }
            
            if(qrCodes[0].Charket__IsActive__c == false)
            {
                String tips = '当前二维码已经被使用，如果需要报名参加会议，可直接回复"报名"。';
                return new Charket.WeChatApiMessage.Text(tips);
            }
            
            List<Charket__WeChatFollower__c> followers = [select Charket__Lead__c, Charket__Contact__c from Charket__WeChatFollower__c 
                    where Charket__OpenId__c = :openId limit 1]; 
                    
            qrCodes[0].Charket__IsActive__c = false;
            
            update qrCodes[0];

            try
            {
                if(followers.size() > 0 && (followers[0].Charket__Lead__c != null || followers[0].Charket__Contact__c != null))
                {              
                    String newLeadOrContactId = followers[0].Charket__Lead__c != null ? followers[0].Charket__Lead__c : followers[0].Charket__Contact__c;

                    if(followers[0].Charket__Lead__c == oldLeadOrContactId 
                            || followers[0].Charket__Contact__c == oldLeadOrContactId)
                    {
                        return null;
                    }
                    else
                    {
                        if(Id.valueOf(newLeadOrContactId).getSObjectType() == Lead.sObjectType 
                                && Id.valueOf(oldLeadOrContactId).getSObjectType() == Lead.sObjectType)
                        {
                            merge new Lead(Id = oldLeadOrContactId) new Lead(Id = newLeadOrContactId);
                        }
                        else if(Id.valueOf(newLeadOrContactId).getSObjectType() == Contact.sObjectType 
                                && Id.valueOf(oldLeadOrContactId).getSObjectType() == Contact.sObjectType)
                        {
                            merge new Contact(Id = oldLeadOrContactId) new Contact(Id = newLeadOrContactId);
                        }
                    }
                }
                else
                {
                    Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(Charket__OpenId__c = openId);

                    if(Id.valueOf(oldLeadOrContactId).getSObjectType() == Lead.sObjectType)
                    {
                        follower.Charket__Lead__c = oldLeadOrContactId;
                    }
                    else if(Id.valueOf(oldLeadOrContactId).getSObjectType() == Contact.sObjectType)
                    {
                        follower.Charket__Contact__c = oldLeadOrContactId;
                    }

                    upsert follower Charket__WeChatFollower__c.Charket__OpenId__c;
                }
            }
            catch(Exception ex)
            {
                insert (new Charket__Log__c(Charket__ApexCodeName__c = 'CharketScanEmailQRCodeHandler', 
                        Charket__Message__c = openId, Charket__Data__c = String.valueOf(followers)));
                return null;
            }
        }
        
        return null;
    }
}