src/LuckyDraw V1.0/src/objects/Charket__WeChatEvent__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mass</fullName>
                </value>
                <value>
                    <fullName>Subscribe</fullName>
                </value>
                <value>
                    <fullName>Unsubscribe</fullName>
                </value>
                <value>
                    <fullName>Scan</fullName>
                </value>
                <value>
                    <fullName>Menu click</fullName>
                </value>
                <value>
                    <fullName>Location</fullName>
                </value>
                <value>
                    <fullName>Template</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Events</relationshipLabel>
        <relationshipName>WeChatEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatEvent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Event</label>
        <referenceTo>Charket__WeChatEvent__c</referenceTo>
        <relationshipLabel>WeChat Events</relationshipLabel>
        <relationshipName>WeChatEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatFollower__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Follower</label>
        <referenceTo>Charket__WeChatFollower__c</referenceTo>
        <relationshipLabel>WeChat Events</relationshipLabel>
        <relationshipName>WeChatEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatQRCode__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat QR Code</label>
        <referenceTo>Charket__WeChatQRCode__c</referenceTo>
        <relationshipLabel>WeChat Events</relationshipLabel>
        <relationshipName>WeChatEvents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Event</label>
    <nameField>
        <displayFormat>WE-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <formula>IF(
  NOT(ISBLANK(Charket__Contact__c)),
  &apos;Contact&apos;,
  IF(NOT(ISBLANK(Charket__Lead__c)),
     &apos;Lead&apos;,
     &apos;Follower&apos;
  )
)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatQRCode__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Temporary</fullName>
                    <default>true</default>
                    <label>Temporary</label>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat QR Codes</relationshipLabel>
        <relationshipName>WeChatQRCode</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WhatId__c</fullName>
        <label>Related To</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>WeChat QR Code</label>
    <nameField>
        <label>WeChat QR Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat QR Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/CustomAgentSelector.cls
global with sharing class CustomAgentSelector implements Charket.WeChatAgentSelector
{
    public String customLabelUserId;
    
    public CustomAgentSelector()
    {
        customLabelUserId = System.Label.CustomAgentUserId;
    }

    global String getAgentId(Charket.WeChatAgentSelectorContext context)
    {  
        String userId = setUserId(context.MsgType, context.FollowerOpenId);    
        String accountId = getWeChatAccountId(context.followerOpenId);

        if(String.isNotBlank(userId) && accountId != null)
        {
            List<Charket__WeChatAgent__c> agents = [select Id from Charket__WeChatAgent__c 
                    where Charket__WeChatAccount__c = :accountId
                    and Charket__User__c = :userId];
            
            if(agents.size() > 0)
            {
                return agents[0].Id; 
            }
        }

        return null;
    }

    public String setUserId(String msgType, String followerOpenId)
    {
        String userId = '';
        
        if(msgType == 'Scan')
        {
            List<Charket__WeChatEvent__c> events = [select Charket__WeChatQRCode__r.Charket__WhatId__c, Charket__Type__c
                    from Charket__WeChatEvent__c 
                    where Charket__WeChatFollower__r.Charket__OpenId__c = :followerOpenId
                    order by CreatedDate desc limit 1];
            
            if(events.size() > 0  
                && (events[0].Charket__Type__c == 'Scan' || events[0].Charket__Type__c == 'Subscribe')
                && events[0].Charket__WeChatQRCode__r.Charket__WhatId__c != null)
            {
                List<Campaign> campaigns = [select OwnerId from Campaign where Id = :events[0].Charket__WeChatQRCode__r.Charket__WhatId__c];
                
                if(campaigns.size() > 0)
                {
                    userId = campaigns[0].OwnerId;
                }
            }
        }
        else
        {
            userId = customLabelUserId;
        }

        return userId;
    }

    public String getWeChatAccountId(String followerOpenId)
    {
        List<Charket__WeChatFollower__c> followers = [select Charket__WeChatAccount__c from Charket__WeChatFollower__c
                where Charket__OpenId__c = :followerOpenId]; 

        if(followers.size() > 0)
        {
            return followers[0].Charket__WeChatAccount__c;
        }

        return null;
    }
}