src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__IsFollowing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Following</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__SubscriptionDate__c</fullName>
        <label>Subscription Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <formula>IF(
  NOT(ISBLANK(Charket__Contact__c)),
  &apos;Contact&apos;,
  IF(NOT(ISBLANK(Charket__Lead__c)),
     &apos;Lead&apos;,
     &apos;Follower&apos;
  )
)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatTranscript__c.object
<CustomObject>
    <fields>
        <fullName>Charket__DeliveredMethod__c</fullName>
        <label>Delivered Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Mass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__FollowerOpenId__c</fullName>
        <externalId>true</externalId>
        <label>Follower Open ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__StartedBy__c</fullName>
        <description>The way the chat was started: by the agent or the follower.</description>
        <label>Started By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Follower</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__UnreadCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unread Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAgent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Agent</label>
        <referenceTo>Charket__WeChatAgent__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatFollower__c</fullName>
        <label>WeChat Follower</label>
        <referenceTo>Charket__WeChatFollower__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WeChat Transcript</label>
    <nameField>
        <displayFormat>WT-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Transcripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/assign-agents/src/objects/WeChatAgentAssignment__c.object
<CustomObject>
    <fields>
        <fullName>WeChatAgentSkill__c</fullName>
        <label>WeChat Agent Skill</label>
        <referenceTo>WeChatAgentSkill__c</referenceTo>
        <relationshipLabel>WeChat Agent Assignments</relationshipLabel>
        <relationshipName>WeChatAgentAssignments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WeChatAgent__c</fullName>
        <label>WeChat Agent</label>
        <referenceTo>Charket__WeChatAgent__c</referenceTo>
        <relationshipLabel>WeChat Agent Assignments</relationshipLabel>
        <relationshipName>WeChatAgentAssignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WeChat Agent Assignment</label>
    <nameField>
        <displayFormat>WAA{0000000}</displayFormat>
        <label>WeChat Agent Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Agent Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/AIESEC/src/objects/WeChatAgentSkill__c.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GV</fullName>
                </value>
                <value>
                    <fullName>GT</fullName>
                </value>
                <value>
                    <fullName>GE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>University__c</fullName>
        <label>University</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>University_Global</valueSetName>
        </valueSet>
    </fields>
    <label>WeChat Agent Skill</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>WeChat Agent Skill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Agent Skills</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/AIESEC/src/classes/ContactTriggerHandlerTest.cls
@isTest
private class ContactTriggerHandlerTest
{
    private static String openId = 'ASSIGN_AGENT_OPENID';

    @isTest
    static void testContactInsert()
    {
        Charket__WeChatAccount__c wechatAccount = new Charket__WeChatAccount__c(
                Name = 'Test Account', Charket__Type__c = 'Service Account',
                Charket__WeChatOriginId__c = 'ASSIGN_AGENT_ORIGIN_ID', IsCustomAgentAssignmentRuleEnabled__c = true
            );

        insert wechatAccount;
        Profile p = [select Id from Profile where Name = 'System Administrator'];

        User user = new User(
                Alias = 'user', Email = 'testuseragent@varian.sfqa.com', EXPA_LC_NAME__c = 'AHU',
                EmailEncodingKey = 'UTF-8', LastName = 'user', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles', UserName = 'testuseragent@varian.sfqa.com'
            );

        insert user;

        List<Charket__WeChatAgent__c> agents = new List<Charket__WeChatAgent__c>();

        agents.add(new Charket__WeChatAgent__c(
                Name = 'agent1', Charket__User__c = user.Id,
                Charket__WeChatAccount__c = wechatAccount.Id, Charket__IsActive__c = true, Charket__LastDesktopActiveTime__c = Datetime.now(),
                Charket__Status__c = 'online'
            ));

        insert agents;

        List<Charket__WeChatFollower__c> followers = new List<Charket__WeChatFollower__c>();

        Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(City_of_University__c = '上海', University__c = '上海交通大学',
                Charket__OpenId__c = openId, Charket__WeChatAccount__c = wechatAccount.Id, Interested_Product__c = 'GT',
                Charket__IsFollowing__c = true, Charket__SubscriptionDate__c = Datetime.now()
            );

        followers.add(follower);

        insert followers;

        Charket__WeChatTranscript__c transcript = new Charket__WeChatTranscript__c();
        transcript.Charket__WeChatAgent__c = agents[0].Id;
        transcript.Charket__Status__c = 'In Progress';
        transcript.Charket__WeChatFollower__c = followers[0].Id;
        transcript.Charket__DeliveredMethod__c = 'Direct';
        transcript.Charket__UnreadCount__c = 0;
        transcript.Charket__StartedBy__c = 'Follower';
        transcript.Charket__FollowerOpenId__c = followers[0].Charket__OpenId__c;
        transcript.Charket__IsActive__c = true;

        upsert transcript transcript.Charket__FollowerOpenId__c;

        Charket__WeChatFollower__c wechatFollower = new Charket__WeChatFollower__c();
        wechatFollower.City_of_University__c = '上海';
        wechatFollower.University__c = '上海交通大学';
        wechatFollower.Interested_Product__c = 'GT';
        wechatFollower.Charket__Gender__c = '女';

        insert wechatFollower;

        system.assertEquals('上海', weChatFollower.City_of_University__c);
        system.assertEquals('上海交通大学', weChatFollower.University__c);

        Contact contact = new Contact();
        contact.LastName = 'Test';
        contact.FirstName = 'Test';
        contact.Password__c = 'Testpassword1';
        contact.Contact_assign_owner_trigger__c = true;
        contact.Interested_Product__c = 'GV';
        contact.City_of_LC__c = '上海';
        contact.University__c = '上海交通大学';

        insert contact;

        system.assertEquals('GV', contact.Interested_Product__c);
    }

    @isTest
    static void testUpdateWithGT()
    {
        Charket__WeChatAccount__c wechatAccount = new Charket__WeChatAccount__c(
                Name = 'Test Account', Charket__Type__c = 'Service Account',
                Charket__WeChatOriginId__c = 'ASSIGN_AGENT_ORIGIN_ID', IsCustomAgentAssignmentRuleEnabled__c = true
            );

        insert wechatAccount;

        Profile p = [select Id from Profile where Name = 'System Administrator'];

        User user = new User(
                Alias = 'user', Email = 'testuseragent@varian.sfqa.com', EXPA_LC_NAME__c = 'AHU',
                EmailEncodingKey = 'UTF-8', LastName = 'user', LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US', ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles', UserName = 'testuseragent@varian.sfqa.com'
            );

        insert user;

        List<User> users = new List<User>();
        for(Integer i = 0; i < 2; i++)
        {
            User userr = new User(
                    Alias = 'user' + i, Email = 'testuseragent' + i + '@varian.sfqa.com', EXPA_LC_NAME__c = 'AHU',
                    EmailEncodingKey = 'UTF-8', LastName = 'user' + i, LanguageLocaleKey = 'en_US',
                    LocaleSidKey = 'en_US', ProfileId = p.Id,
                    TimeZoneSidKey = 'America/Los_Angeles', UserName = 'testuseragent' + i + '@varian.sfqa.com'
                );
            users.add(userr);
        }
        insert users;

        List<Charket__WeChatAgent__c> agents1 = new List<Charket__WeChatAgent__c>();

        agents1.add(new Charket__WeChatAgent__c(
                Name = 'agent1', Charket__User__c = users[1].Id,
                Charket__WeChatAccount__c = wechatAccount.Id, Charket__IsActive__c = true, Charket__LastDesktopActiveTime__c = Datetime.now(),
                Charket__Status__c = 'online'
            ));
        
        agents1.add(new Charket__WeChatAgent__c(
                Name = 'agent2', Charket__User__c = users[0].Id,
                Charket__WeChatAccount__c = wechatAccount.Id, Charket__IsActive__c = true, Charket__LastDesktopActiveTime__c = Datetime.now(),
                Charket__Status__c = 'online'
            ));
        insert agents1;

        List<WeChatAgentSkill__c> skills = new List<WeChatAgentSkill__c>();
        skills.add(new WeChatAgentSkill__c(Product__c = 'GT', University__c = '上海交通大学'));
        skills.add(new WeChatAgentSkill__c(Product__c = 'GT', University__c = '其他'));
        skills.add(new WeChatAgentSkill__c(Product__c = 'GT', University__c = '中山大学'));
        skills.add(new WeChatAgentSkill__c(Product__c = null, University__c = null));
        insert skills;

        List<WechatAgentAssignment__c> assignments = new List<WechatAgentAssignment__c>();
        assignments.add(new WechatAgentAssignment__c(WeChatAgent__c = agents1[0].Id, WeChatAgentSkill__c = skills[0].Id));
        assignments.add(new WechatAgentAssignment__c(WeChatAgent__c = agents1[1].Id, WeChatAgentSkill__c = skills[0].Id));
        assignments.add(new WechatAgentAssignment__c(WeChatAgent__c = agents1[1].Id, WeChatAgentSkill__c = skills[1].Id));
        assignments.add(new WechatAgentAssignment__c(WeChatAgent__c = agents1[1].Id, WeChatAgentSkill__c = skills[2].Id));
        insert assignments;

        Contact contact = new Contact();
        contact.LastName = 'Test';
        contact.FirstName = 'Test';
        contact.Password__c = 'Testpassword1';
        contact.Contact_assign_owner_trigger__c = true;
        contact.City_of_LC__c = '上海';
        contact.University__c = '上海交通大学';

        insert contact;

        Contact contact1 = new Contact();
        contact1.LastName = 'Test1';
        contact1.FirstName = 'Test1';
        contact1.Password__c = 'Testpassword1';
        contact1.Contact_assign_owner_trigger__c = true;
        contact1.City_of_LC__c = '上海';
        contact1.University__c = '复旦大学';

        Contact contact2 = new Contact();
        contact2.LastName = 'Test2';
        contact2.FirstName = 'Test2';
        contact2.Password__c = 'Testpassword1';
        contact2.Contact_assign_owner_trigger__c = true;
        contact2.City_of_LC__c = '上海';
        contact2.University__c = '上海交通大学';

        List<Contact> contacts = new List<Contact>();
        contacts.add(contact1);
        contacts.add(contact2);

        insert contacts;

        List<Charket__WeChatFollower__c> followers = new List<Charket__WeChatFollower__c>();

        Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(City_of_University__c = '上海', University__c = '上海交通大学',
                Charket__OpenId__c = openId, Charket__WeChatAccount__c = wechatAccount.Id, Interested_Product__c = 'GT',
                Charket__IsFollowing__c = true, Charket__SubscriptionDate__c = Datetime.now(), Charket__Contact__c = contact.Id
            );
        Charket__WeChatFollower__c follower1 = new Charket__WeChatFollower__c(City_of_University__c = '上海', University__c = '上海交通大学',
                Charket__OpenId__c = openId + '1', Charket__WeChatAccount__c = wechatAccount.Id, Interested_Product__c = 'GT',
                Charket__IsFollowing__c = true, Charket__SubscriptionDate__c = Datetime.now(), Charket__Contact__c = contact1.Id
            );

        followers.add(follower);
        followers.add(follower1);

        insert followers;

        system.assertEquals(true, contact.Contact_assign_owner_trigger__c);

        contact.Interested_Product__c = 'GT';

        update contact;
        contact1.Interested_Product__c = 'GT';
        contact2.Interested_Product__c = 'GT';
        update contacts;

        system.assertEquals('GT', contact.Interested_Product__c);
    }

    @isTest
    static void testUpdateWithGE()
    {
        Contact contact = new Contact();
        contact.LastName = 'Test';
        contact.FirstName = 'Test';
        contact.Password__c = 'Testpassword1';
        contact.Contact_assign_owner_trigger__c = true;
        contact.City_of_LC__c = '上海';
        contact.University__c = '上海交通大学';

        insert contact;

        system.assertEquals(true, contact.Contact_assign_owner_trigger__c);

        contact.Interested_Product__c = 'GE';

        update contact;

        system.assertEquals('GE', contact.Interested_Product__c);
    }

    @isTest
    static void testUpdateWithGV()
    {
        Contact contact = new Contact();
        contact.LastName = 'Test';
        contact.FirstName = 'Test';
        contact.Password__c = 'Testpassword1';
        contact.Contact_assign_owner_trigger__c = true;
        contact.City_of_LC__c = '上海';
        contact.University__c = '上海交通大学';

        insert contact;

        system.assertEquals(true, contact.Contact_assign_owner_trigger__c);

        contact.Interested_Product__c = 'GV';

        update contact;

        system.assertEquals('GV', contact.Interested_Product__c);
    }
}