src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/assign-agents/src/classes/CharketCustomAssignmentHandler.cls
global class CharketCustomAssignmentHandler implements Charket.WeChatAgentSelector
{
    global String getAgentId(Charket.WeChatAgentSelectorContext context)
    {
        List<Charket__WeChatFollower__c> followers = [select University__c, Interested_Product__c, Charket__WeChatAccount__c
                from Charket__WeChatFollower__c where Charket__OpenId__c = :context.FollowerOpenId and Charket__WeChatAccount__c != null
                limit 1];

        if(followers.size() == 1)
        {
            return WeChatAgentCustomAssigmentUtil.getAgentId(followers[0]);
        }

        return null;
    }
}