src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatTranscript__c.object
<CustomObject>
    <fields>
        <fullName>Charket__WeChatAgent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Agent</label>
        <referenceTo>Charket__WeChatAgent__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatFollower__c</fullName>
        <label>WeChat Follower</label>
        <referenceTo>Charket__WeChatFollower__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WeChat Transcript</label>
    <nameField>
        <displayFormat>WT-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Transcripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/WeChatFollowerTriggerHandler.cls
public with sharing class WeChatFollowerTriggerHandler extends TriggerHandler
{
    public final static String SITE_GUEST_USER = 'PID_Guest_User';
    private Map<Id, Charket__WeChatFollower__c> newFollowerMap;
    
    public WeChatFollowerTriggerHandler()
    {
        this.newFollowerMap = (Map<Id, Charket__WeChatFollower__c>) Trigger.newMap;
    }
    
    public override void afterInsert()
    {
        try
        {
            assignLeadOwner(newFollowerMap.keySet());
        }
        catch(Exception ex)
        {
            insert (new Charket__Log__c(Charket__ApexCodeName__c = 'WeChatFollowerTriggerHandler', Charket__Message__c = ex.getMessage()));
        }
    }

    public override void afterUpdate() 
    {
        try
        {
            assignLeadOwner(newFollowerMap.keySet());
        }
        catch(Exception ex)
        {
            insert (new Charket__Log__c(Charket__ApexCodeName__c = 'WeChatFollowerTriggerHandler', Charket__Message__c = ex.getMessage()));
        }
    }

    public static void assignLeadOwner(Set<Id> followerIds)
    {
        List<Charket__WeChatFollower__c> followers = filterFollowers(followerIds);
        
        if(followers.isEmpty())
        {
            return;
        }
        
        Map<String, String> followerIdToLeadId = new Map<String, String>();
        Map<String, String> followerIdToUserId = new Map<String, String>();
        
        for(Charket__WeChatFollower__c follower : followers)
        {
            if(follower.Charket__WeChatTranscripts__r.size() > 0)
            {
                followerIdToLeadId.put(follower.Id, follower.Charket__Lead__c);
                followerIdToUserId.put(follower.Id, follower.Charket__WeChatTranscripts__r[0].Charket__WeChatAgent__r.Charket__User__c);
            }
        }

        List<Lead> leadsToUpdate = new List<Lead>();

        for(Id followerId : followerIdToUserId.keySet())
        {
            Lead lead = new Lead(Id = followerIdToLeadId.get(followerId), OwnerId = followerIdToUserId.get(followerId));
            leadsToUpdate.add(lead);
        }
        
        try
        {
            update leadsToUpdate;
        }
        catch(Exception ex) {}
    }

    public static List<Charket__WeChatFollower__c> filterFollowers(Set<Id> followerIds)
    {
        List<Charket__WeChatFollower__c> followers = [select Charket__Lead__r.Owner.Profile.UserLicense.LicenseDefinitionKey, 
                Charket__Lead__c, (select Id, Charket__WeChatAgent__r.Charket__User__c
                from Charket__WeChatTranscripts__r where Charket__WeChatAgent__c != null order by CreatedDate desc limit 1) 
                from Charket__WeChatFollower__c where Id in :followerIds
                and Charket__Lead__r.Owner.Profile.UserLicense.LicenseDefinitionKey = :SITE_GUEST_USER]; 

        return followers;
    }
}