src/LuckyDraw V1.0/src/objects/Charket__WeChatTranscript__c.object
<CustomObject>
    <fields>
        <fullName>Charket__AgentMessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Agent Message Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charket__Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__StartTime__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Charket__Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Waiting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__WeChatAgent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Agent</label>
        <referenceTo>Charket__WeChatAgent__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Transcript</label>
    <nameField>
        <displayFormat>WT-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Transcripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatTranscriptItem__c.object
<CustomObject>
    <fields>
        <fullName>Charket__Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__MessageId__c</fullName>
        <description>WeChat Message ID from WeChat platform</description>
        <externalId>true</externalId>
        <label>Message ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__SendBy__c</fullName>
        <label>Send By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Follower</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__SenderId__c</fullName>
        <label>Sender ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__ShortBody__c</fullName>
        <label>Short Body</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>TEXT</fullName>
                </value>
                <value>
                    <fullName>IMAGE</fullName>
                </value>
                <value>
                    <fullName>VOICE</fullName>
                </value>
                <value>
                    <fullName>VIDEO</fullName>
                </value>
                <value>
                    <fullName>MUSIC</fullName>
                </value>
                <value>
                    <fullName>NEWS</fullName>
                </value>
                <value>
                    <fullName>SHORTVIDEO</fullName>
                </value>
                <value>
                    <fullName>LOCATION</fullName>
                </value>
                <value>
                    <fullName>LINK</fullName>
                </value>
                <value>
                    <fullName>CLICK</fullName>
                </value>
                <value>
                    <fullName>VIEW</fullName>
                </value>
                <value>
                    <fullName>CARD</fullName>
                </value>
                <value>
                    <fullName>SUBSCRIBE</fullName>
                </value>
                <value>
                    <fullName>UNSUBSCRIBE</fullName>
                </value>
                <value>
                    <fullName>SCAN</fullName>
                </value>
                <value>
                    <fullName>TRANSFER</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__WeChatAgentId__c</fullName>
        <externalId>true</externalId>
        <label>WeChat Agent ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatCreatedTime__c</fullName>
        <description>Created Time from WeChat platform</description>
        <label>WeChat Created Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatTranscript__c</fullName>
        <label>WeChat Transcript</label>
        <referenceTo>Charket__WeChatTranscript__c</referenceTo>
        <relationshipLabel>WeChat Transcript Items</relationshipLabel>
        <relationshipName>WeChatTranscriptItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WeChat Transcript Item</label>
    <nameField>
        <displayFormat>WTI-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Transcript Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/CharketChatListener.cls
@RestResource(urlMapping='/livechat/*')
global with sharing class CharketChatListener
{
    @HttpPost
    global static void doPost()
    {
        try
        {
            if(RestContext.request.requestBody != null)
            { 
                String accountId = RestContext.request.params.get('accountId');
                String openId = RestContext.request.params.get('openId');
                String requestBody = RestContext.request.requestBody.toString();
                String transcriptId = RestContext.request.params.get('transcriptId');
                String responseBody;
                if(String.isNotBlank(accountId) && String.isNotBlank(openId) && String.isNotBlank(requestBody))
                {
                    List<Charket__WeChatTranscript__c> transcripts = [select Id, Charket__StartTime__c, 
                        Charket__AgentMessageCount__c, Charket__WeChatAgent__r.Charket__IsActive__c,
                        Charket__WeChatAgent__c, Charket__WeChatAgent__r.Charket__WeChatUsername__c 
                        from Charket__WeChatTranscript__c
                        where Id = :transcriptId and Charket__WeChatAgent__c != null limit 1];
                    if(transcripts.size() > 0)
                    {
                        if(!transcripts[0].Charket__WeChatAgent__r.Charket__IsActive__c)
                        {
                            responseBody = 'Please contact your system administrator for setting you up as a WeChat agent.';
                        }
                        else
                        {
                            Charket.WeChatApiMessage.Text message = new Charket.WeChatApiMessage.Text(requestBody);
                            message.ToUserId = openId;
                            message.CreateTime = Datetime.now();
                            Charket.WeChatClient client = new Charket.WeChatClient(accountId);
                            if(client != null)
                            {
                                Charket.WeChatApiAgent agent = client.getAgent();
                                String agentUserName = (transcripts[0].Charket__WeChatAgent__c != null) ? transcripts[0].Charket__WeChatAgent__r.Charket__WeChatUsername__c : null;
                                agent.sendMessage(message, agentUserName);
                            }
                            
                            updateTranscriptForAgent(transcripts[0], requestBody);
                            responseBody = 'success';
                        }
                    }
                }
                RestContext.response.responseBody = Blob.valueOf(responseBody);
            }
        }
        catch(Exception e)
        {
            String data = RestContext.request.requestBody != null ? RestContext.request.requestBody.toString() : 'No Request Body';
            insert (new Charket__Log__c(Charket__ApexCodeName__c = 'CharketChatListener', Charket__Message__c = e.getMessage(), Charket__Data__c = data));
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody = Blob.valueOf(e.getMessage());
        }
    }

    public static void updateTranscriptForAgent(Charket__WeChatTranscript__c transcript, String content)
    {
        Charket__WeChatTranscriptItem__c item = new Charket__WeChatTranscriptItem__c(
            Charket__WeChatCreatedTime__c = Datetime.now().getTime(),
            Charket__WeChatAgentId__c = transcript.Charket__WeChatAgent__c,
            Charket__SenderId__c = UserInfo.getUserId(),
            Charket__SendBy__c = 'Agent',
            Charket__Type__c = 'TEXT',
            Charket__MessageId__c = UserInfo.getUserId() + Datetime.now().getTime(),
            Charket__Body__c = content,
            Charket__ShortBody__c = (content != null) ? content.left(255): content,
            Charket__IsActive__c = true
        );

        if(transcript.Charket__StartTime__c == null)
        {
            transcript.Charket__StartTime__c = Datetime.now();
            transcript.Charket__Status__c = 'In Progress';
        }
        transcript.Charket__AgentMessageCount__c += 1;
        update transcript;

        item.Charket__WeChatTranscript__c = transcript.Id;
        insert item;
    }
}