src/LuckyDraw V1.0/src/objects/Charket__WeChatFollower__c.object
<CustomObject>
    <fields>
        <fullName>Charket__IsFollowing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Following</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__OpenId__c</fullName>
        <externalId>true</externalId>
        <label>Open ID</label>
        <length>225</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__SubscriptionDate__c</fullName>
        <label>Subscription Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Charket__Type__c</fullName>
        <formula>IF(
  NOT(ISBLANK(Charket__Contact__c)),
  &apos;Contact&apos;,
  IF(NOT(ISBLANK(Charket__Lead__c)),
     &apos;Lead&apos;,
     &apos;Follower&apos;
  )
)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAccount__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WeChat Account</label>
        <referenceTo>Charket__WeChatAccount__c</referenceTo>
        <relationshipLabel>WeChat Followers</relationshipLabel>
        <relationshipName>WeChatFollowers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WeChat Follower</label>
    <nameField>
        <label>Nickname</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WeChat Followers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/objects/Charket__WeChatTranscript__c.object
<CustomObject>
    <fields>
        <fullName>Charket__AgentMessageCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Agent Message Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charket__DeliveredMethod__c</fullName>
        <label>Delivered Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Mass</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__FollowerOpenId__c</fullName>
        <externalId>true</externalId>
        <label>Follower Open ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Charket__IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charket__StartedBy__c</fullName>
        <description>The way the chat was started: by the agent or the follower.</description>
        <label>Started By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Follower</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Charket__UnreadCount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unread Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatAgent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeChat Agent</label>
        <referenceTo>Charket__WeChatAgent__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Charket__WeChatFollower__c</fullName>
        <label>WeChat Follower</label>
        <referenceTo>Charket__WeChatFollower__c</referenceTo>
        <relationshipLabel>WeChat Transcripts</relationshipLabel>
        <relationshipName>WeChatTranscripts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WeChat Transcript</label>
    <nameField>
        <displayFormat>WT-{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WeChat Transcripts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/LuckyDraw V1.0/src/classes/CharketChatListenerTest.cls
@isTest
private class CharketChatListenerTest
{
    @isTest
    static void testSendMessage()
    {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new WeChatTestHttpMock('success', 'OK', 200));
        
        Charket__WeChatAccount__c account = new Charket__WeChatAccount__c(
                Name = 'Test Account', Charket__WeChatOriginId__c = 'test', Charket__Type__c = 'subscribe'
            );
        insert account;
        Charket__WeChatAgent__c agent = new Charket__WeChatAgent__c(
                Name = 'agent', Charket__WeChatAccount__c = account.Id, Charket__User__c = UserInfo.getUserId()
            );
        insert agent;
        Charket__WeChatFollower__c follower = new Charket__WeChatFollower__c(
                Charket__OpenId__c = 'oLNKJwT_or6El', Charket__WeChatAccount__c = account.Id,
                Charket__IsFollowing__c = true, Charket__SubscriptionDate__c = System.now()
            );
        insert follower;
        Charket__WeChatTranscript__c transcript = new Charket__WeChatTranscript__c(
                Charket__DeliveredMethod__c = 'Direct', Charket__FollowerOpenId__c = follower.Charket__OpenId__c,
                Charket__WeChatAgent__c = agent.Id, Charket__StartedBy__c = 'Follower',
                Charket__UnreadCount__c = 1, Charket__IsActive__c = true, 
                Charket__WeChatFollower__c = follower.Id, Charket__AgentMessageCount__c = 0
            );
        insert transcript;
        
        RestRequest req = new RestRequest();
        req.addParameter('openId', follower.Charket__OpenId__c);
        req.addParameter('accountId', account.Id);
        req.addParameter('transcriptId', transcript.Id);
        req.requestBody = Blob.valueOf('test');
        
        RestContext.request = req;
        RestContext.response = new RestResponse();
        CharketChatListener.doPost();
        CharketChatListener.updateTranscriptForAgent(transcript, 'test');
        Test.stopTest();
    }
}